### ISSUE TITLE
[BUG] ICloudPyAPIResponseException from China account.

### ISSUE THREAD

**Issue by lichengwu** [mandarons/icloud-drive-docker#134]
When do authentication using:

```
sudo docker exec -it iCloud /bin/sh -c "icloud --username=ol_l@msn.cn --region=china --session-directory=/app/session_data"
Enter iCloud password for ol_l@msn.cn:
Save password in keyring? [y/N]: y

Two-step authentication required.
Please enter validation code
(string) -->
```
The docker container crashed with the following errors:

```
Loading config from /app/config.yaml ...
2023-03-18 16:07:15,413 :: ERROR :: icloudpy.base :: base.py :: 186 :: Authentication required for Account. (421)
2023-03-18 16:07:15,735 :: ERROR :: icloudpy.base :: base.py :: 186 :: Not Found (404)
Traceback (most recent call last):
  File "/app/venv/lib/python3.10/site-packages/icloudpy/base.py", line 336, in authenticate
    self.session.post(
  File "/app/venv/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/app/venv/lib/python3.10/site-packages/icloudpy/base.py", line 131, in request
    self._raise_error(response.status_code, response.reason)
  File "/app/venv/lib/python3.10/site-packages/icloudpy/base.py", line 187, in _raise_error
    raise api_error
icloudpy.exceptions.ICloudPyAPIResponseException: Not Found (404)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/./src/main.py", line 7, in <module>
    sync.sync()
  File "/app/src/sync.py", line 68, in sync
    api = get_api_instance(
  File "/app/src/sync.py", line 30, in get_api_instance
    ICloudPyService(
  File "/app/venv/lib/python3.10/site-packages/icloudpy/base.py", line 277, in __init__
    self.authenticate()
  File "/app/venv/lib/python3.10/site-packages/icloudpy/base.py", line 344, in authenticate
    raise ICloudPyFailedLoginException(msg, error) from error
icloudpy.exceptions.ICloudPyFailedLoginException: ('Invalid email/password combination.', ICloudPyAPIResponseException('Not Found (404)'))

```

My account/password is correct, and i received the 2FA. But it crashed when i want to enter validation code.

**Comment by mandarons** [comment]
Chinese servers have been hit and miss. Can you set logging to debug in the config file and run it again? Please share relevant logs.

**Comment by lichengwu** [comment]
> 

2023-03-19 01:01:01,741 :: WARNING :: root :: notify.py :: 47 :: Not sending 2FA notification because SMTP is not configured
Loading config from /app/config.yaml ...
2023-03-19 01:01:02,758 :: DEBUG :: root :: config_parser.py :: 101 :: Checking root destination ...
2023-03-19 01:01:02,760 :: DEBUG :: urllib3.connectionpool :: connectionpool.py :: 1003 :: Starting new HTTPS connection (1): wapar-api.mandarons.com:443
2023-03-19 01:01:04,501 :: DEBUG :: urllib3.connectionpool :: connectionpool.py :: 456 :: https://wapar-api.mandarons.com:443 "POST /api/heartbeat HTTP/1.1" 201 45
2023-03-19 01:01:04,506 :: DEBUG :: icloudpy.base :: base.py :: 246 :: Using session file session_data/ol_lmsncn.session
2023-03-19 01:01:04,512 :: DEBUG :: icloudpy.base :: base.py :: 270 :: Read cookies from session_data/ol_lmsncn
2023-03-19 01:01:04,512 :: DEBUG :: icloudpy.base :: base.py :: 291 :: Checking session token validity
2023-03-19 01:01:04,513 :: DEBUG :: icloudpy.base :: base.py :: 390 :: Checking session token validity
2023-03-19 01:01:04,579 :: DEBUG :: icloudpy.base.http :: base.py :: 75 :: POST https://setup.icloud.com.cn/setup/ws/1/validate null
2023-03-19 01:01:04,583 :: DEBUG :: urllib3.connectionpool :: connectionpool.py :: 1003 :: Starting new HTTPS connection (1): setup.icloud.com.cn:443
2023-03-19 01:01:04,853 :: DEBUG :: urllib3.connectionpool :: connectionpool.py :: 456 :: https://setup.icloud.com.cn:443 "POST /setup/ws/1/validate HTTP/1.1" 421 442
2023-03-19 01:01:04,856 :: DEBUG :: icloudpy.base :: base.py :: 94 :: Saved session data to file
2023-03-19 01:01:04,893 :: DEBUG :: icloudpy.base :: base.py :: 98 :: Cookies saved to session_data/ol_lmsncn
2023-03-19 01:01:04,893 :: DEBUG :: icloudpy.base.http :: base.py :: 127 :: Misdirected Request (421). Retrying ...
2023-03-19 01:01:04,895 :: DEBUG :: requests.sessions.http :: base.py :: 75 :: POST https://setup.icloud.com.cn/setup/ws/1/validate null
2023-03-19 01:01:05,113 :: DEBUG :: urllib3.connectionpool :: connectionpool.py :: 456 :: https://setup.icloud.com.cn:443 "POST /setup/ws/1/validate HTTP/1.1" 421 442
2023-03-19 01:01:05,116 :: DEBUG :: icloudpy.base :: base.py :: 94 :: Saved session data to file
2023-03-19 01:01:05,119 :: DEBUG :: icloudpy.base :: base.py :: 98 :: Cookies saved to session_data/ol_lmsncn
2023-03-19 01:01:05,120 :: ERROR :: icloudpy.base :: base.py :: 186 :: Authentication required for Account. (421)
2023-03-19 01:01:05,120 :: DEBUG :: icloudpy.base :: base.py :: 396 :: Invalid authentication token
2023-03-19 01:01:05,121 :: DEBUG :: icloudpy.base :: base.py :: 296 :: Invalid authentication token, will log in from scratch.
2023-03-19 01:01:05,121 :: DEBUG :: icloudpy.base :: base.py :: 318 :: Authenticating as ol_l@msn.cn
2023-03-19 01:01:05,123 :: DEBUG :: icloudpy.base.http :: base.py :: 75 :: POST https://www.icloud.com.cn/signin {"accountName": "ol_l@msn.cn", "password": "********", "rememberMe": true, "trustTokens": []}
2023-03-19 01:01:05,127 :: DEBUG :: urllib3.connectionpool :: connectionpool.py :: 1003 :: Starting new HTTPS connection (1): www.icloud.com.cn:443
2023-03-19 01:01:05,475 :: DEBUG :: urllib3.connectionpool :: connectionpool.py :: 456 :: https://www.icloud.com.cn:443 "POST /signin?isRememberMeEnabled=true HTTP/1.1" 404 1511
2023-03-19 01:01:05,477 :: DEBUG :: icloudpy.base :: base.py :: 94 :: Saved session data to file
2023-03-19 01:01:05,515 :: DEBUG :: icloudpy.base :: base.py :: 98 :: Cookies saved to session_data/ol_lmsncn
2023-03-19 01:01:05,515 :: ERROR :: icloudpy.base :: base.py :: 186 :: Not Found (404)
Traceback (most recent call last):
  File "/app/venv/lib/python3.10/site-packages/icloudpy/base.py", line 336, in authenticate
    self.session.post(
  File "/app/venv/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/app/venv/lib/python3.10/site-packages/icloudpy/base.py", line 131, in request
    self._raise_error(response.status_code, response.reason)
  File "/app/venv/lib/python3.10/site-packages/icloudpy/base.py", line 187, in _raise_error
    raise api_error
icloudpy.exceptions.ICloudPyAPIResponseException: Not Found (404)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/./src/main.py", line 7, in <module>
    sync.sync()
  File "/app/src/sync.py", line 68, in sync
    api = get_api_instance(
  File "/app/src/sync.py", line 30, in get_api_instance
    ICloudPyService(
  File "/app/venv/lib/python3.10/site-packages/icloudpy/base.py", line 277, in __init__
    self.authenticate()
  File "/app/venv/lib/python3.10/site-packages/icloudpy/base.py", line 344, in authenticate
    raise ICloudPyFailedLoginException(msg, error) from error
icloudpy.exceptions.ICloudPyFailedLoginException: ('Invalid email/password combination.', ICloudPyAPIResponseException('Not Found (404)'))
